{{- if .Values.secrets.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hello-helm.fullname" . }}
  labels:
    {{- include "hello-helm.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $name, $config := .Values.secrets.values }}
  {{ $name }}: {{ $config | b64enc | quote  }}
  {{- end }}
{{- end }}